# Generated by Django 3.1.7 on 2021-03-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_auto_20210328_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='image',
            field=models.ImageField(upload_to='uploads/%y/% m/%d/'),
        ),
    ]
