# Generated by Django 3.1.7 on 2021-03-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_auto_20210328_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='number_of_entries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='ticket_limit',
            field=models.IntegerField(default=0),
        ),
    ]
