# Generated by Django 3.1.7 on 2021-03-28 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_auto_20210328_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='competition_answers_one',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='competition',
            name='competition_answers_three',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='competition',
            name='competition_answers_two',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='competition',
            name='competition_correct_answer',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='competition',
            name='competition_end_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='competition',
            name='competition_question',
            field=models.TextField(default='what is the capital of the uk'),
        ),
    ]
