# Generated by Django 3.1.7 on 2021-04-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_auto_20210405_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='is_published',
        ),
        migrations.AddField(
            model_name='competition',
            name='state',
            field=models.CharField(default='unpublished', max_length=25),
        ),
    ]
