# Generated by Django 3.1.7 on 2021-04-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_auto_20210405_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='state',
            field=models.CharField(choices=[('unpublished', 'unpublished'), ('published', 'published'), ('awaiting', 'awaiting'), ('done', 'done')], default='unpublished', max_length=25),
        ),
    ]
