# Generated by Django 3.1.7 on 2021-04-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0012_auto_20210405_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='entries',
            field=models.ManyToManyField(blank=True, to='competitions.Entrie'),
        ),
    ]
