"""
Django settings for footgasm project.
Generated by 'django-admin startproject' using Django 3.1.7.
For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from footgasm.settings.base import *
from pathlib import Path
import os


SITE_ID = 1

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
        'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'TSC',
        'USER': 'postgres',
        'PASSWORD': 'Runite123',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}