# Generated by Django 3.1.7 on 2021-04-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='answer_correct',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='answer',
            field=models.IntegerField(default=1),
        ),
    ]
