# Generated by Django 3.1.7 on 2021-04-04 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0007_auto_20210404_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Failed', max_length=20)),
                ('payee_email', models.EmailField(max_length=254)),
                ('paypal_payment_id', models.CharField(max_length=100)),
                ('paypal_payer_id', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('currency_code', models.CharField(max_length=5)),
                ('payment_date', models.DateField()),
                ('full_name', models.CharField(max_length=70)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.address')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
